project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Grand Tour"
  navbar:
    left:
      - href: bookwinebar.qmd
        text: BookWineBar
      - href: catalogo.qmd
        text: Catalogo
      - href: incontri.qmd
        text: Incontri
      - text: Turismo
        href: turismo.qmd
      - text: Musiche
        href: musiche.qmd
      - text: Scritture
        href: scritture.qmd
    right:
      - text: contatti
        href: contatti.qmd
      - icon: linkedin
        href: https://www.linkedin.com/groups/4880518/
      - icon: twitter
        href: https://twitter.com/tweet_scritture
      - icon: facebook
        href: https://www.facebook.com/search/scritturemagazine
      - icon: envelope
        href: mailto:grandtour.frascati@gmail.com
        aria-label: Email
  page-footer: 
    left: 
      - text: "Questa raccolta di opere è distribuita con Licenza Creative Commons Attribuzione - Non commerciale - Condividi allo stesso modo 4.0 "   
        href: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.it
    right: 
      - text: ISSN 2499-6610
      
format:
  html:
    theme: united
    css: styles.css
    toc: true
    bootstrap: 5

editor: visual
lang: it

language:
  en:
    title-block-author-single: "Author"
    listing-page-field-author: "Author"
  it:
    title-block-author-single: "di"
    listing-page-field-author: "di"


default-image-extension: ""