project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Grandtour Book wine bar"
  
  navbar:
#    logo: "/images/scritture_logo.png"
    left:
      - text: Claudio Comandini
        href: /diario.html#category=Claudio%20Comandini
      - text: Scritture
        href: /scritture.html
        
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/groups/4880518/
      - icon: twitter
        href: https://twitter.com/tweet_scritture
      - icon: facebook
        href: https://www.facebook.com/search/scritturemagazine
      - icon: envelope
        href: mailto:grandtour.frascati@gmail.com
        aria-label: Email
format:
  html:
    theme: united
    css: styles.css
    toc: true
    bootstrap: 5

editor: visual
lang: it

language:
  en:
    title-block-author-single: "Author"
    listing-page-field-author: "Author"
  it:
    title-block-author-single: "di"
    listing-page-field-author: "di"


default-image-extension: ""