name: Build Quarto Documents

on:
  push:
    branches:
      - main  # O qualsiasi branch desideri

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.0.0/quarto-1.0.0-linux-amd64.deb
        sudo dpkg -i quarto-1.0.0-linux-amd64.deb

    - name: Render Quarto project
      run: |
        quarto render docs --to html
        quarto render docs --to pdf
        quarto render docs --to epub

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs


# on:
#   workflow_dispatch:
#   push:
#     branches: main
# 
# name: Quarto Publish
# 
# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v4
# 
#       - name: Set up Quarto
#         uses: quarto-dev/quarto-actions/setup@v2
# 
#       - name: Render and Publish
#         uses: quarto-dev/quarto-actions/publish@v2
#         with:
#           target: gh-pages
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          